In [89]:
import numpy as np

In [90]:
arr=np.array([[1,2,3,4,5]],np.int8) #usenp.intx,where x is datavalue which can be adjusted 
arr1=np.array([5,6,7,8])

In [91]:
arr[0,1]

2

In [92]:
arr1[1]

6

## Different attributes are :
## 1.arr.shape
## 2.arr.size
## 3.arr.dtype
## 4.print(len(arr))


In [93]:
arr.shape

(1, 5)

In [94]:
arr1.size

4

In [95]:
arr1.dtype

dtype('int32')

In [96]:
arr1[1]=99
arr1

array([ 5, 99,  7,  8])

In [97]:
listarr=np.array([[1,2,3],[4,5,6]])
listarr

array([[1, 2, 3],
       [4, 5, 6]])

In [98]:
listarr.size

6

In [99]:
zeroarr=np.zeros([2,5])
zeroarr

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [100]:
loll=np.arange(12)
loll

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [101]:
ball=np.linspace(1,5,4) #from 1 to 5 i need 4 equal distance numbers
ball

array([1.        , 2.33333333, 3.66666667, 5.        ])

#numpy.empty_like: Return a new array with the same shape and type as a given array.`

In [102]:
arr2=np.empty((3,4))
arr2

array([[1.12258401e-311, 3.16202013e-322, 0.00000000e+000,
        0.00000000e+000],
       [0.00000000e+000, 1.78636887e-051, 1.47716159e-075,
        7.60095606e-042],
       [6.45512136e+170, 2.59733920e-056, 2.17699580e-076,
        1.38050209e-071]])

In [103]:
emp_like=np.empty_like(ball)
emp_like

array([1.        , 2.33333333, 3.66666667, 5.        ])

## The np.arange function from NumPy is used to create arrays with evenly spaced values within a specified interval. 

In [104]:
arr=np.arange(99)

In [105]:
arr.reshape(3,33)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [106]:
## ravel = ravel() function to flatten an array and return a 1-D array

In [107]:
arr=arr.ravel()
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [108]:
x=[[1,2,3],[4,5,6],[7,8,9]]
x=np.array(x)
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

# sum(axis =0) means sum of 1,4,7 || sum of 2,5,8 || sum of 3,6,9
# sum(axis =1) means sum of 1,2,3 || sum of 4,5,6 || sum of 7,8,9 

In [110]:
x.sum(axis=0)

array([12, 15, 18])

In [111]:
x.sum(axis=1)

array([ 6, 15, 24])

In [112]:
x.T # x.T is used to print the transpose of the array named "x"

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [114]:
x.flat
for item in x.flat:
    print(item)

1
2
3
4
5
6
7
8
9


In [115]:
one=np.array([1,2,3,66,6,0])
one.argmax() #returns the index of maximum value

3

In [116]:
one.argmin() #returns the index of minimum value

5

In [118]:
np.sort(one) #to sort an arry`

array([ 0,  1,  2,  3,  6, 66])

## sum of array

In [123]:
a=np.array([[1,2,3],[4,5,6],[1,2,1]])
b=np.array([[2,3,4],[7,8,9],[1,2,1]])

In [124]:
a+b

array([[ 3,  5,  7],
       [11, 13, 15],
       [ 2,  4,  2]])