In [8]:
import numpy as np
import scipy

## 1.Creating a Vector

In [9]:
#Create a vector as a Row
vector_row = np.array([1,2,3])

#Create vector as a Column
vector_column = np.array([[1],[2],[3]])

In [10]:
vector_row

array([1, 2, 3])

In [11]:
vector_column

array([[1],
       [2],
       [3]])

## 2. Creating a Matrix

In [12]:
matrix = np.array([[1,2,3],[4,5,6]])
print(matrix)

[[1 2 3]
 [4 5 6]]


## 3. Creating a Sparse Matrix

In [13]:
#Create a Matrix
matrix = np.array([[0,0],[0,1],[3,0]])
print(matrix)

#Create Compressed Sparse Row(CSR) matrix
#matrix_sparse = sparse.csr_matrix(matrix) #doesnt work because scipy module cant be imported
#print(matrix_sparse)

[[0 0]
 [0 1]
 [3 0]]


## 4. Selecting Elements

In [14]:
#Create a vector as a Row
vector_row = np.array([ 1,2,3,4,5,6 ])

#Create a Matrix
matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])
print("a:",matrix)

#Select 3rd element of Vector
print("b:",vector_row[2])

#Select 2nd row 2nd column
print("c:",matrix[1,1])
#Select all elements of a vector
print("d:",vector_row[:])
#Select everything up to and including the 3rd element
print("e:",vector_row[:3])
#Select the everything after the 3rd element
print("f:",vector_row[3:])
#Select the last element
print("g:",vector_row[-1])
#Select the first 2 rows and all the columns of the matrix
print("h:",matrix[:2,:])
#Select all rows and the 2nd column of the matrix
print("i:",matrix[:,1:2])

a: [[1 2 3]
 [4 5 6]
 [7 8 9]]
b: 3
c: 5
d: [1 2 3 4 5 6]
e: [1 2 3]
f: [4 5 6]
g: 6
h: [[1 2 3]
 [4 5 6]]
i: [[2]
 [5]
 [8]]


## 5. Describing a Matrix

In [15]:
#Create a Matrix
matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])
#View the Number of Rows and Columns
print(matrix.shape)
#View the number of elements (rows*columns)
print(matrix.size)
#View the number of Dimensions(2 in this case)
print(matrix.ndim)

(3, 3)
9
2


## 6. Applying operations to elements

In [16]:
#Create a Matrix
matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(matrix)

#Create a function that adds 100 to something
add_100 =lambda i: i+100

#Convert it into a vectorized function
vectorized_add_100= np.vectorize(add_100)

#Apply function to all elements in matrix
print(vectorized_add_100(matrix))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[101 102 103]
 [104 105 106]
 [107 108 109]]


## 7. Finding the max and min values

In [17]:
#Create a Matrix
matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(matrix)
#Return the max element
print("The max element in th matrix is:",np.max(matrix))
#Return the min element
print("The min element in th matrix is:",np.min(matrix))
#To find the max element in each column
print("The min element in each column are:",np.max(matrix,axis=0))
#To find the max element in each row
print("The max element in each column are:",np.max(matrix,axis=1))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
The max element in th matrix is: 9
The min element in th matrix is: 1
The min element in each column are: [7 8 9]
The max element in each column are: [3 6 9]


## 8. Calculating Average, Variance and Standard deviation

In [18]:
#Create a Matrix
matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(matrix)
#Mean
print(np.mean(matrix))
#Standard Dev.
print(np.std(matrix))
#Variance
print(np.var(matrix))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
5.0
2.581988897471611
6.666666666666667


## 9. Generating Random values

In [19]:
np.random.seed(1)
#Generate 3 random integers b/w 1 and 10
print(np.random.randint(0,11,3))
#Draw 3 numbers from a normal distribution with mean 1.0 and std 2.0
print(np.random.normal(1.0,2.0,3))

[5 8 9]
[-0.60434568  0.10224438 -1.21187015]
